# Stress Level Prediction Model Configuration
# lightning.pytorch==2.1.0
seed_everything: true

trainer:
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "{epoch}-{val_loss:.2f}.best"
        monitor: "val_loss"
        mode: "min"
        save_top_k: 1
        verbose: true
        save_on_train_epoch_end: false
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: "{epoch}.last"
        monitor: "step"
        mode: "max"
        save_top_k: 1
        verbose: true
        save_on_train_epoch_end: false
    - class_path: Classification.callbacks.ONNXExportCallback
      init_args:
        output_dir: "UpiFraudClassification/models"  # change once
        model_name: "upi_fraud_model"   # change once
        input_dim: null  # Will be auto-detected

  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: "UpiFraudClassification/logs" # change once
      name: "UpiFraudTraining"        # change once
      default_hp_metric: false

  max_epochs: 5
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  accelerator: auto
  devices: auto
  precision: 16-mixed
  default_root_dir: "UpiFraudClassification/logs/StressLevelTraining" # change once

model:
  class_path: Classification.modelmodule.ModelModuleCLS
  init_args:
    lr: 0.0001
    weight_decay: 0.0
    lr_scheduler_factor: 0.5
    lr_scheduler_patience: 5
    save_dir: "UpiFraudClassification/models" # change once
    name: "upi_fraud_model"  # change once
    model:
      class_path: Classification.modelfactory.ClassificationModel
      init_args:
        input_dim: 0  
        num_classes: 0  
        hidden_layers: [128, 64, 32]
        dropout_rates: [0.15, 0.1, 0.05]
        activation: "relu"

optimizer: 
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.00001

lr_scheduler:
  class_path: torch.optim.lr_scheduler.OneCycleLR
  init_args:
    max_lr: 0.001
    pct_start: 0.1
    total_steps: 1000

data:
  class_path: Classification.datamodule.DataModuleCLS
  init_args:
    csv_path: "UpiFraudClassification/data/upi_risk.csv" # change once
    batch_size: 256
    num_workers: 0
    val_split: 0.2
    random_seed: 42
    categorical_cols:   #chage once
      - transaction_type
      - merchant_category
      - device_type
      - is_new_payee
    numeric_cols:        #change once
      - transaction_amount
      - hour_of_day
      - account_age_days
      - num_txn_last_24h
      - num_failed_txn_last_24h
      - distance_from_usual_km
      
    target_col: "risk_label"  #change once
    save_preprocessor: true
    preprocessor_path: "UpiFraudClassification/models/preprocessor.joblib"  # change once

fit:
  ckpt_path: null   # for resume training

test:
  ckpt_path: best   # checkpoint to use for test and predict

